name: langchain
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - pandas
  - geopandas
  - jupyterlab
  - matplotlib
  - ipywidgets
  - pyrosm
  - shapely
  - pyproj
  - fiona
  - requests
  - psycopg2
  - sqlalchemy
  - polyline
  - openpyxl
  - rapidfuzz
  - feedparser
  - beautifulsoup4
  - pydantic
  - openai
  - langchain
  - langchain-community
  - langchain-openai
  - pip
